### ISSUE TITLE
Tryna understand basics

### ISSUE THREAD

**Issue by amanbagrecha** [amanbagrecha/github-slideshow#4]
when do you issue issue? before branching or after it

**Comment by concretefair** [comment]
Issues have nothing to do with braching maccha @amanbagrecha 💯

**Comment by amanbagrecha** [comment]
#3 was done to justify the commit

- [x] did you learn something!?
- [ ] `does this help?`

**Comment by concretefair** [comment]
> #3 was done to justify the commit
> 
> * [x]  did you learn something!?
> * [ ]  `does this help?`

Yes I did maccha
![Uploading myAvatar.png…]()

**Comment by concretefair** [comment]
Duplicate of #1

**Comment by amanbagrecha** [comment]
enjoyed a lot!
